table invoices
	lineageTag: ab91eab4-becb-408f-9370-ca6f8cf1aad8

	measure 'invoice amount' = sum(invoices[amount])
		formatString: #,0
		lineageTag: c022d224-3f77-45f3-ada7-f4a6840f30cb

		annotation PBI_FormatHint = {"isDecimal":true}

	column invoice_id
		dataType: string
		lineageTag: e575da11-a35c-454a-99be-513fb1bf4289
		summarizeBy: none
		sourceColumn: invoice_id

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: string
		lineageTag: 4be2bf0b-0dac-484f-9ac4-c199d087f66b
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: 3127725f-a3b9-4bb4-bb14-39bbc375e762
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column invoice_date
		dataType: string
		lineageTag: f3d5aea0-4832-4d5b-93a1-286123b7ba6f
		summarizeBy: none
		sourceColumn: invoice_date

		annotation SummarizationSetBy = Automatic

	column due_date
		dataType: string
		lineageTag: a5dd9e4f-8a34-457d-b8f0-93e9a8417528
		summarizeBy: none
		sourceColumn: due_date

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		isHidden
		lineageTag: b2ed5e6c-b602-4d2a-a46f-1804fa5c9654
		summarizeBy: sum
		sourceColumn: amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: 82135b00-177c-4448-8ac1-5b50c4bb7ad2
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column invoice_type
		dataType: string
		lineageTag: 7300364b-676b-4303-b71d-071e95dd1065
		summarizeBy: none
		sourceColumn: invoice_type

		annotation SummarizationSetBy = Automatic

	partition invoices = m
		mode: import
		source =
				let
				    Källa = Csv.Document(File.Contents("C:\repos\BuildCoBI\data\raw\invoices.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Upphöjda rubriker" = Table.PromoteHeaders(Källa, [PromoteAllScalars=true]),
				    #"Ersatt värde" = Table.ReplaceValue(#"Upphöjda rubriker",".",",",Replacer.ReplaceText,{"amount"}),
				    #"Ändrad typ" = Table.TransformColumnTypes(#"Ersatt värde",{{"amount", type number}})
				in
				    #"Ändrad typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigering

