table project_costs
	lineageTag: 6b5e7092-dd1c-4e2c-a96d-9a85a36e8397

	column cost_id
		dataType: string
		lineageTag: f1860190-426a-48b9-94ed-db775b26f02a
		summarizeBy: none
		sourceColumn: cost_id

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: string
		lineageTag: 53664036-59b7-4975-b1b2-5de95d65bf54
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column cost_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: befbfb3d-ea9d-4ea4-a30e-442799b2c4e9
		summarizeBy: none
		sourceColumn: cost_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cost_type
		dataType: string
		lineageTag: 38cca507-bd0c-40bd-a850-c35f39992f2d
		summarizeBy: none
		sourceColumn: cost_type

		annotation SummarizationSetBy = Automatic

	column supplier
		dataType: string
		lineageTag: 1f883d72-71c0-4c89-a431-f6ed0e8ccaf5
		summarizeBy: none
		sourceColumn: supplier

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		formatString: #,0
		lineageTag: 34ea899e-526e-4104-aa2a-11555bb54bd7
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column voucher_no
		dataType: string
		lineageTag: bb8ceb0c-3cc8-4d56-bfab-e677befb940e
		summarizeBy: none
		sourceColumn: voucher_no

		annotation SummarizationSetBy = Automatic

	column is_reversed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 348f135a-62b2-4d6a-ac27-5e18d5e32d8a
		summarizeBy: none
		sourceColumn: is_reversed

		annotation SummarizationSetBy = Automatic

	column customer_sk
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 32f6ed8d-af63-4b98-a3c2-c239c4b70868
		summarizeBy: none
		sourceColumn: customer_sk

		annotation SummarizationSetBy = Automatic

	partition project_costs = m
		mode: import
		source =
				let
				    Källa = Csv.Document(File.Contents("C:\repos\BuildCoBI\data\raw\project_costs.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Upphöjda rubriker" = Table.PromoteHeaders(Källa, [PromoteAllScalars=true]),
				    #"Ändrad typ" = Table.TransformColumnTypes(#"Upphöjda rubriker",{{"cost_id", type text}, {"project_id", type text}, {"cost_date", type date}, {"cost_type", type text}, {"supplier", type text}, {"amount", type number}, {"voucher_no", type text}, {"is_reversed", type logical}}, "en-US"),
				    #"Borttagna dubbletter" = Table.Distinct(#"Ändrad typ", {"voucher_no", "cost_date", "supplier", "amount"}),
				    ProjektBuffer = Table.Buffer(projects),
				    DimBuffer = Table.Buffer(dim_customer_scd2),
				    #"Tillagd customer_id" = Table.AddColumn(#"Borttagna dubbletter", "customer_id", (rad) =>
				        try Table.SelectRows(ProjektBuffer, (p) => p[project_id] = rad[project_id]){0}[customer_id] otherwise null, type text),
				    #"Tillagd customer_sk" = Table.AddColumn(#"Tillagd customer_id", "customer_sk", (rad) =>
				        let
				            Träffar = Table.SelectRows(DimBuffer, (d) =>
				                d[customer_id] = rad[customer_id]
				                and rad[cost_date] >= d[valid_from]
				                and (d[valid_to] = null or rad[cost_date] <= d[valid_to]))
				        in
				            try Träffar{0}[customer_sk] otherwise null, Int64.Type),
				    #"Borttagen customer_id" = Table.RemoveColumns(#"Tillagd customer_sk", {"customer_id"})
				in
				    #"Borttagen customer_id"

	annotation PBI_ResultType = Table

